//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMANDAEntities : DbContext
    {
        public AMANDAEntities()
            : base("name=AMANDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAJA> CAJA { get; set; }
        public DbSet<DETALLE_PROMOCION> DETALLE_PROMOCION { get; set; }
        public DbSet<PACK> PACK { get; set; }
        public DbSet<PACK_DETALLE> PACK_DETALLE { get; set; }
        public DbSet<PROMOCION> PROMOCION { get; set; }
        public DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public DbSet<TRANSACCION_CAJA> TRANSACCION_CAJA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public DbSet<ENTRADA_PRODUCTO> ENTRADA_PRODUCTO { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<APERTURA_CIERRE> APERTURA_CIERRE { get; set; }
        public DbSet<HISTORIAL_STOCK> HISTORIAL_STOCK { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
        public DbSet<ALERTA_STOCK> ALERTA_STOCK { get; set; }
        public DbSet<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
