//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APERTURA_CIERRE
    {
        public APERTURA_CIERRE()
        {
            this.TRANSACCION_CAJA = new HashSet<TRANSACCION_CAJA>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int ID_APERTURA_CIERRE { get; set; }
        public Nullable<System.DateTime> FECHA_APERTURA { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public Nullable<int> MONTO_INICIAL { get; set; }
        public Nullable<int> MONTO_FINAL { get; set; }
        public Nullable<bool> ACTIVA { get; set; }
        public Nullable<int> MONTO_CIGARRILLOS { get; set; }
        public Nullable<int> MONTO_EFECTIVO { get; set; }
        public Nullable<int> MONTO_DEBITO { get; set; }
        public Nullable<int> ID_CAJA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    
        public virtual CAJA CAJA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<TRANSACCION_CAJA> TRANSACCION_CAJA { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
