//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAJA
    {
        public CAJA()
        {
            this.APERTURA_CIERRE = new HashSet<APERTURA_CIERRE>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int ID_CAJA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<APERTURA_CIERRE> APERTURA_CIERRE { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
