//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        public int ID_DETALLE_VENTA { get; set; }
        public string SKU { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<int> PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<bool> TIENE_PROMOCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> USUARIO_VENTA { get; set; }
        public Nullable<System.DateTime> FECHA_UPDATE { get; set; }
        public Nullable<int> USUARIO_UPDATE { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_PROMOCION { get; set; }
        public Nullable<bool> EXCENTO_IVA { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROMOCION PROMOCION { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
