//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PROMOCION
    {
        public int ID_DETALLE_PROMOCION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_PROMOCION { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    
        public virtual PROMOCION PROMOCION { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
