//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA_PRODUCTO
    {
        public int ID_ENTRADA_PRODUCTO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> COSTO_UNITARIO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> ANULADA { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
