//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_STOCK
    {
        public int ID_HISTORIAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal STOCK_ANTERIOR { get; set; }
        public decimal STOCK_NUEVO { get; set; }
        public string USUARIO { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
