//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPRESORA
    {
        public IMPRESORA()
        {
            this.CAJA_IMPRESORA = new HashSet<CAJA_IMPRESORA>();
        }
    
        public int ID_IMPRESORA { get; set; }
        public string NOMBRE_WINDOWS { get; set; }
        public string TIPO { get; set; }
        public bool ACTIVA { get; set; }
    
        public virtual ICollection<CAJA_IMPRESORA> CAJA_IMPRESORA { get; set; }
    }
}
