//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_DETALLE
    {
        public int ID_PACKDETALLE { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> ID_PACK { get; set; }
        public Nullable<int> CANTIDAD_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_CRECION { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_UPDATE { get; set; }
        public Nullable<int> USUARIO_UPDATE { get; set; }
    
        public virtual PACK PACK { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
