//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK
    {
        public PACK()
        {
            this.PACK_DETALLE = new HashSet<PACK_DETALLE>();
        }
    
        public int ID_PACK { get; set; }
        public string SKU_PACK { get; set; }
        public string NOMBRE_PACK { get; set; }
        public Nullable<System.DateTime> FECHA_CRECION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> PRECIO_PACK { get; set; }
        public Nullable<System.DateTime> FECHA_UPDATE { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<int> USUARIO_UPDATE { get; set; }
        public Nullable<bool> EXCENTO_IVA { get; set; }
    
        public virtual ICollection<PACK_DETALLE> PACK_DETALLE { get; set; }
    }
}
