//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DETALLE_PROMOCION = new HashSet<DETALLE_PROMOCION>();
            this.PACK_DETALLE = new HashSet<PACK_DETALLE>();
            this.ENTRADA_PRODUCTO = new HashSet<ENTRADA_PRODUCTO>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.HISTORIAL_STOCK = new HashSet<HISTORIAL_STOCK>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string SKU { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHA_CRECION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> PRECIO { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<System.DateTime> FECHA_UPDATE { get; set; }
        public Nullable<int> USUARIO_CREACION { get; set; }
        public Nullable<int> USUARIO_UPDATE { get; set; }
        public Nullable<bool> EXCENTO_IVA { get; set; }
        public Nullable<int> ID_TIPO_PRODUCTO { get; set; }
    
        public virtual ICollection<DETALLE_PROMOCION> DETALLE_PROMOCION { get; set; }
        public virtual ICollection<PACK_DETALLE> PACK_DETALLE { get; set; }
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        public virtual ICollection<ENTRADA_PRODUCTO> ENTRADA_PRODUCTO { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual ICollection<HISTORIAL_STOCK> HISTORIAL_STOCK { get; set; }
    }
}
