//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMOCION
    {
        public PROMOCION()
        {
            this.DETALLE_PROMOCION = new HashSet<DETALLE_PROMOCION>();
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }
    
        public int ID_PROMOCION { get; set; }
        public string NOMBRE { get; set; }
        public string VALOR { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual ICollection<DETALLE_PROMOCION> DETALLE_PROMOCION { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
    }
}
