//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        public PROVEEDOR()
        {
            this.ENTRADA_PRODUCTO = new HashSet<ENTRADA_PRODUCTO>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public string CIUDAD { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<bool> VISITA_LUNES { get; set; }
        public Nullable<bool> VISITA_MARTES { get; set; }
        public Nullable<bool> VISITA_MIERCOLES { get; set; }
        public Nullable<bool> VISITA_JUEVES { get; set; }
        public Nullable<bool> VISITA_VIERNES { get; set; }
        public Nullable<bool> VISITA_SABADO { get; set; }
        public Nullable<bool> VISITA_DOMINGO { get; set; }
    
        public virtual ICollection<ENTRADA_PRODUCTO> ENTRADA_PRODUCTO { get; set; }
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
