//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION_CAJA
    {
        public int ID_TRANSACCION_CAJA { get; set; }
        public string TIPO_TRANSACCION { get; set; }
        public Nullable<int> MONTO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public Nullable<int> ID_APERTURA_CIERRE { get; set; }
    
        public virtual APERTURA_CIERRE APERTURA_CIERRE { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
