//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ROL_USUARIO = new HashSet<ROL_USUARIO>();
            this.ENTRADA_PRODUCTO = new HashSet<ENTRADA_PRODUCTO>();
            this.APERTURA_CIERRE = new HashSet<APERTURA_CIERRE>();
            this.VENTA = new HashSet<VENTA>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string PASSWORD { get; set; }
        public string USERNAME { get; set; }
        public string RUT { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ICollection<ROL_USUARIO> ROL_USUARIO { get; set; }
        public virtual ICollection<ENTRADA_PRODUCTO> ENTRADA_PRODUCTO { get; set; }
        public virtual ICollection<APERTURA_CIERRE> APERTURA_CIERRE { get; set; }
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
