//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_amanda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        public VENTA()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.TRANSACCION_CAJA = new HashSet<TRANSACCION_CAJA>();
        }
    
        public int ID_VENTA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> DESCUENTO_APLICADO { get; set; }
        public Nullable<bool> CONTIENE_CIGARROS { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_CAJA { get; set; }
        public Nullable<int> ID_APERTURA_CIERRE { get; set; }
    
        public virtual APERTURA_CIERRE APERTURA_CIERRE { get; set; }
        public virtual CAJA CAJA { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual ICollection<TRANSACCION_CAJA> TRANSACCION_CAJA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
